{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "554c47c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Создайте новый файл italian_vocabulary.py с этим содержимым\n",
    "def get_vocabulary():\n",
    "    return {\n",
    "        \"Работа и карьера\": {\n",
    "            \"il colloquio\": {\n",
    "                \"перевод\": \"собеседование\",\n",
    "                \"примеры\": [\n",
    "                    {\n",
    "                        \"русский\": \"У меня собеседование в крупной компании завтра утром\",\n",
    "                        \"итальянский\": \"Ho un colloquio in una grande azienda domani mattina\",\n",
    "                        \"альтернативы_рус\": [\n",
    "                            \"У меня собеседование в большой компании завтра утром\"\n",
    "                        ],\n",
    "                        \"альтернативы_ит\": [\n",
    "                            \"Ho un colloquio in una grand azienda domani mattina\",\n",
    "                            \"Ho un colloquio in una grande azienda domani mattina\"\n",
    "                        ]\n",
    "                    }\n",
    "                ]\n",
    "            }\n",
    "        },\n",
    "        \"Путешествия\": {\n",
    "            \"la prenotazione\": {\n",
    "                \"перевод\": \"бронирование\",\n",
    "                \"примеры\": [\n",
    "                    {\n",
    "                        \"русский\": \"Я хочу забронировать номер в отеле\",\n",
    "                        \"итальянский\": \"Vorrei prenotare una camera d'albergo\",\n",
    "                        \"альтернативы_рус\": [\n",
    "                            \"Я хотел бы забронировать номер в отеле\",\n",
    "                            \"Я бы хотел забронировать номер\"\n",
    "                        ],\n",
    "                        \"альтернативы_ит\": [\n",
    "                            \"Voglio prenotare una camera d'albergo\",\n",
    "                            \"Desidero prenotare una camera d'albergo\"\n",
    "                        ]\n",
    "                    }\n",
    "                ]\n",
    "            }\n",
    "        },\n",
    "        \"Еда и рестораны\": {\n",
    "            \"il menu\": {\n",
    "                \"перевод\": \"меню\",\n",
    "                \"примеры\": [\n",
    "                    {\n",
    "                        \"русский\": \"Можно посмотреть меню, пожалуйста?\",\n",
    "                        \"итальянский\": \"Posso vedere il menu, per favore?\",\n",
    "                        \"альтернативы_рус\": [\n",
    "                            \"Принесите, пожалуйста, меню\",\n",
    "                            \"Можно меню, пожалуйста?\"\n",
    "                        ],\n",
    "                        \"альтернативы_ит\": [\n",
    "                            \"Mi porta il menu, per favore?\",\n",
    "                            \"Potrei vedere il menu, per favore?\"\n",
    "                        ]\n",
    "                    }\n",
    "                ]\n",
    "            }\n",
    "        }\n",
    "    }"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
